"use client";
import Link from "next/link";
import { usePathname, useRouter } from "next/navigation";
import { SiteHeader } from "@/components/site-header";
import { Button } from "@/components/ui/button";
import { logoutUser } from "@/lib/demo-store";
import { useDemo } from "@/components/use-demo";
const links = [["Tổng quan", "/tai-khoan"], ["Đơn hàng", "/tai-khoan/don-hang"], ["Giới thiệu", "/tai-khoan/gioi-thieu"], ["Hoa hồng", "/tai-khoan/hoa-hong"], ["Rút tiền", "/tai-khoan/rut-tien"]];
export function AccountShell({ title, children }: { title: string; children: React.ReactNode }) { const { user } = useDemo(); const pathname = usePathname(); const router = useRouter(); if (!user) return <main className="min-h-screen bg-[#F7F2E7]"><SiteHeader/><div className="container-wide py-24 text-center"><h1 className="font-serif text-4xl">Vui lòng đăng nhập</h1><p className="mt-4 text-[#587067]">Bạn cần đăng nhập để xem khu vực tài khoản thử nghiệm.</p><Button asChild className="mt-7 rounded-full bg-[#073D2B]"><Link href="/dang-nhap">Đăng nhập</Link></Button></div></main>; return <main className="min-h-screen bg-[#F7F2E7]"><SiteHeader/><section className="container-wide py-10 sm:py-16"><div className="mb-8"><p className="eyebrow">Tài khoản thử nghiệm</p><h1 className="mt-3 font-serif text-4xl sm:text-5xl">{title}</h1><p className="mt-2 text-[#587067]">Xin chào, {user.name}</p><p className="demo-notice mt-5">Bản thử nghiệm: tài khoản, đơn hàng và hoa hồng chỉ lưu trên trình duyệt này. Số dư không phải tiền thật; không có chi trả hoặc xác thực tài khoản thật.</p></div><div className="grid gap-7 lg:grid-cols-[240px_minmax(0,1fr)]"><aside className="h-fit rounded-2xl border border-[#073D2B]/10 bg-white p-3"><nav className="grid gap-1">{links.map(([label, href])=><Link key={href} href={href} className={`rounded-xl px-4 py-3 text-sm font-semibold ${pathname===href?"bg-[#073D2B] text-white":"text-[#294D40] hover:bg-[#F7F2E7]"}`}>{label}</Link>)}</nav><Button variant="outline" className="mt-3 w-full rounded-xl" onClick={()=>{logoutUser();router.push("/")}}>Đăng xuất</Button></aside><div className="min-w-0">{children}</div></div></section></main>; }
