"use client";
import Link from "next/link";
import { FormEvent, useState } from "react";
import { Check, Copy, Share2 } from "lucide-react";
import { AccountShell } from "@/components/account-shell";
import { Button } from "@/components/ui/button";
import { balances, getCommissions, getOrders, getUsers, getWallet, getWithdrawals, requestWithdrawal } from "@/lib/demo-store";
import { referralPolicyNote } from "@/lib/referral-config";
import { basePath, formatVnd } from "@/lib/site";
import { useDemo } from "@/components/use-demo";
const card="rounded-2xl border border-[#073D2B]/10 bg-white p-6";
function useData(){const {user:u}=useDemo();return {u, orders:u?getOrders().filter(o=>o.userId===u.id):[], commissions:u?getCommissions().filter(c=>c.beneficiaryId===u.id):[], wallet:u?getWallet().filter(w=>w.userId===u.id):[], withdrawals:u?getWithdrawals().filter(w=>w.userId===u.id):[], balance:u?balances(u.id):{pending:0,available:0,paid:0}}}
export function DashboardView(){const d=useData();return <AccountShell title="Tổng quan"><div className="grid gap-4 sm:grid-cols-3"><Stat label="Đơn hàng" value={String(d.orders.length)}/><Stat label="Hoa hồng chờ duyệt" value={formatVnd(d.balance.pending)}/><Stat label="Số dư khả dụng" value={formatVnd(d.balance.available)}/></div><div className={`${card} mt-5`}><h2 className="font-serif text-2xl">Mã giới thiệu của bạn</h2><p className="mt-3 text-3xl font-semibold tracking-wider">{d.u?.referralCode}</p><Button asChild className="mt-5 rounded-full bg-[#073D2B]"><Link href="/tai-khoan/gioi-thieu">Chia sẻ và xem chi tiết</Link></Button></div></AccountShell>}
function Stat({label,value}:{label:string;value:string}){return <div className={card}><p className="text-sm text-[#6B7C75]">{label}</p><p className="mt-3 text-2xl font-semibold">{value}</p></div>}
export function OrdersView(){const d=useData();return <AccountShell title="Đơn hàng"><div className="grid gap-4">{d.orders.length?d.orders.map(o=><article className={card} key={o.id}><div className="flex flex-wrap justify-between gap-3"><div><h2 className="font-semibold">{o.code}</h2><p className="mt-1 text-sm text-[#6B7C75]">{new Date(o.createdAt).toLocaleString("vi-VN")}</p></div><span className="h-fit rounded-full bg-[#F7F2E7] px-3 py-1 text-xs font-semibold">{o.status}</span></div><p className="mt-5">Sâm Nữ Hoàng G8 × {o.items[0]?.quantity}</p><p className="mt-2 font-semibold">{formatVnd(o.total)}</p></article>):<div className={card}>Chưa có đơn hàng thử nghiệm.</div>}</div></AccountShell>}
export function ReferralView(){const d=useData();const [copied,setCopied]=useState(false);const referred=d.u?getUsers().filter(u=>u.referrerId===d.u!.id).length:0;const link=typeof window!=="undefined"&&d.u?`${window.location.origin}${basePath}/dang-ky?ref=${d.u.referralCode}`:"";async function copy(value:string){await navigator.clipboard.writeText(value);setCopied(true);setTimeout(()=>setCopied(false),1500)}return <AccountShell title="Giới thiệu bạn bè"><section className="overflow-hidden rounded-[2rem] bg-[#073D2B] p-7 text-white sm:p-10"><p className="text-xs font-bold uppercase tracking-[.18em] text-[#D5C388]">Giới thiệu bạn bè</p><h2 className="mt-4 font-serif text-4xl">Nhận 5% hoa hồng</h2><p className="mt-4 max-w-2xl leading-7 text-white/70">Chương trình một cấp: bạn nhận hoa hồng từ đơn đủ điều kiện của người đăng ký trực tiếp qua mã của bạn.</p><div className="mt-7 flex flex-col gap-3 sm:flex-row"><code className="flex-1 rounded-xl bg-white/10 px-4 py-3 text-sm break-all">{link}</code><Button onClick={()=>copy(link)} className="bg-[#C8A34A] text-[#052C20]">{copied?<Check/>:<Copy/>}{copied?"Đã sao chép":"Sao chép"}</Button>{typeof navigator!=="undefined"&&"share" in navigator&&<Button variant="outline" onClick={()=>navigator.share({title:"Queen Ginseng Vietnam",url:link})}><Share2/>Chia sẻ</Button>}</div></section><div className="mt-5 grid gap-4 sm:grid-cols-4"><Stat label="Đã giới thiệu" value={String(referred)}/><Stat label="Chờ duyệt" value={formatVnd(d.balance.pending)}/><Stat label="Khả dụng" value={formatVnd(d.balance.available)}/><Stat label="Đã nhận" value={formatVnd(d.balance.paid)}/></div><p className={`${card} mt-5 text-sm leading-6 text-[#587067]`}>{referralPolicyNote}</p></AccountShell>}
export function CommissionView(){const d=useData();return <AccountShell title="Hoa hồng"><div className="grid gap-4 sm:grid-cols-3"><Stat label="Chờ duyệt" value={formatVnd(d.balance.pending)}/><Stat label="Khả dụng" value={formatVnd(d.balance.available)}/><Stat label="Đã rút" value={formatVnd(d.balance.paid)}/></div><div className={`${card} mt-5 overflow-x-auto`}><h2 className="font-serif text-2xl">Sổ giao dịch</h2><table className="mt-5 w-full min-w-[560px] text-left text-sm"><thead><tr className="border-b"><th className="py-3">Thời gian</th><th>Loại</th><th>Tham chiếu</th><th className="text-right">Số tiền</th></tr></thead><tbody>{d.wallet.map(w=><tr className="border-b border-[#073D2B]/8" key={w.id}><td className="py-3">{new Date(w.createdAt).toLocaleDateString("vi-VN")}</td><td>{w.type}</td><td>{w.referenceId}</td><td className="text-right font-semibold">{formatVnd(w.amount)}</td></tr>)}</tbody></table></div></AccountShell>}
export function WithdrawalView(){const d=useData();const [message,setMessage]=useState("");function submit(e:FormEvent<HTMLFormElement>){e.preventDefault();const f=new FormData(e.currentTarget);try{requestWithdrawal({amount:Number(f.get("amount")),bank:String(f.get("bank")),accountNumber:String(f.get("accountNumber")),accountName:String(f.get("accountName"))});setMessage("Đã tạo yêu cầu rút tiền thử nghiệm.");e.currentTarget.reset()}catch(err){setMessage(err instanceof Error?err.message:"Không thể tạo yêu cầu.")}}return <AccountShell title="Rút tiền"><div className="grid gap-5 lg:grid-cols-2"><form onSubmit={submit} className={card}><h2 className="font-serif text-2xl">Tạo yêu cầu</h2><p className="mt-2 text-sm text-[#587067]">Số dư khả dụng: {formatVnd(d.balance.available)}</p><div className="mt-6 grid gap-4"><label className="form-label">Số tiền<input name="amount" type="number" min="1" max={Math.max(1,d.balance.available)} required className="form-input"/></label><label className="form-label">Ngân hàng<input name="bank" required className="form-input"/></label><label className="form-label">Số tài khoản<input name="accountNumber" required className="form-input"/></label><label className="form-label">Tên tài khoản<input name="accountName" required className="form-input"/></label></div>{message&&<p role="status" className="mt-4 text-sm">{message}</p>}<Button className="mt-6 w-full rounded-full bg-[#073D2B]">Gửi yêu cầu thử nghiệm</Button><p className="mt-4 text-xs leading-5 text-[#6B7C75]">Bản thử nghiệm – yêu cầu rút tiền chưa được gửi tới hệ thống thanh toán thật.</p></form><div className={card}><h2 className="font-serif text-2xl">Lịch sử yêu cầu</h2><div className="mt-5 grid gap-3">{d.withdrawals.map(w=><div key={w.id} className="rounded-xl bg-[#F7F2E7] p-4"><div className="flex justify-between gap-3"><b>{formatVnd(w.amount)}</b><span className="text-xs font-semibold">{w.status}</span></div><p className="mt-2 text-xs text-[#6B7C75]">{w.bank} · {w.accountNumber}</p></div>)}</div></div></div></AccountShell>}
